---
title: "Analyses Part II"
author: "chfal"
date: "6/30/2020"
output: html_document
---

# Here are the packages needed.

```{r}
library(readr) # for reading data
library(dplyr) # for cleaning data
library(MASS) # for analysis
library(lme4) # for analysis
library(glmmTMB) # for analysis
library(gamm4) # for analysis
library(xts) # to cut 
library(ggplot2)
library(corrplot)
```


```{r}
total_data <- read_csv("total_joined_data.csv")
```

# Let's answer some questions about the data.

## 1) Is there a correlation between Google and Apple mobility data?

```{r}
lm(total_data$expected_decrease ~ total_data$value)
summary(lm(total_data$expected_decrease ~ total_data$value))
plot(total_data$expected_decrease, total_data$value)
```

# Is there a correlation between R0 and percent growth?
# Answer: Yes!

```{r}
plot(total_data$R0, total_data$pct_change)
lm(total_data$R0 ~total_data$pct_change)
summary(lm(total_data$R0 ~total_data$pct_change))
```


# Let's make some sick graphs lol

## Mask Data on R0 by State

```{r, out.width="100%"}
ggplot(total_data, aes(R0, fill=state)) +
  geom_boxplot() +
  facet_wrap(~state) +
  theme(legend.position="none", axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
  labs(title="R0 by State")

ggplot(total_data, aes(pct_change, fill=state)) +
  geom_boxplot() +
  facet_wrap(~state) +
  theme(legend.position="none", axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
  labs(title="Percent Change in Weekly Cases by State")

#all states
ggplot(total_data, aes(x=masks_worn, y=lagged_R0)) +
  geom_boxplot() +
  facet_wrap(~state)


# this is too crazy, let's make it states with mask mandatesa
states_w_masks <- total_data %>%
  filter_at(vars(state), any_vars(TRUE %in% c(masks_worn)))

ggplot(data=states_w_masks, aes(x=masks_worn, y=R0, fill=masks_worn)) +
  geom_boxplot() +
  facet_wrap(~state) +
  theme(legend.position="none") +
  scale_x_discrete(breaks=c("TRUE", "FALSE"), labels=c("Masks", "No Masks")) +
  labs(x="Mask Mandate", y="R0", title="R0 before and after Statewide Mask Mandates") +
  ggsave("state_w_masks_r0.png")
```

## Weather and R0 by State

```{r, out.width="100%"}
ggplot(total_data, aes(x=temp_in_K, y=R0, color=state)) + 
  geom_point() +
  facet_wrap(~state) +
  labs(title="Weather and R0 by State") +
  theme(legend.position="none") +
  ggsave("weather_r0.png")
```


```{r, out.width="100%"}
total_data %>%
  filter(state=="Illinois" || state=="Indiana") %>%
  ggplot() +
  geom_point(aes(start_date, R0, color=state)) +
  geom_vline(xintercept=5/1/2020)
```